# iOS Fastfile
default_platform(:ios)
require 'json'

TEMP_KEYCHAIN_PASSWORD = "oto-fastlane"

before_all do
  ensure_git_branch(branch: 'main')
end

platform :ios do
  
  desc "Upgrade iOS Version"
  lane :upgrade_version do
    increment_build_number(xcodeproj: 'app_demo.xcodeproj')
  end
  

  # Lane used for deploying the beta app to testflight
  lane :beta do
    
      # Incement the build number of the iOS project
      # increment_build_number(xcodeproj: 'app_demo.xcodeproj')
      
      # Command to select the correct XCode Version
      # xcode_select # Make sure to use the correct Xcode version
     
      # Extract values needed from ios_fastlane.json
      json_data = File.read('ios_fastlane.json')
      data_hash = JSON.parse(json_data)
      
      # keychain_password: data_hash["matchPassword"]

      # Command to sign app properly with the match appstore
      match(
        type: "appstore",
        app_identifier: "oto-fastlane-circleci-test",
        git_url: "https://github.com/kieyanmamicheOtO/match-repo",
        git_basic_authorization: data_hash['gitBasicAuthorization'],
        readonly: true,
      )
      
      # Build the app
      gym(
        scheme: 'app_demo',
        workspace: 'app_demo.xcworkspace',
        clean: 'true',
        export_method: "app-store",
        export_options: {
          uploadBitcode: false,
          uploadSymbols: true,
        }
      )
      
      # Generate the App Store Connect Api Key
      api_key = app_store_connect_api_key(
        key_id: data_hash['keyId'],
        issuer_id: data_hash['issuerId'],
        key_filepath: data_hash['keyFilePath'],
        duration: 1200
      )
    
      # Comamnd to deploy app to testflight
      pilot(api_key: api_key)
  end

end