# iOS Fastfile
default_platform(:ios)


before_all do
  ensure_git_branch(branch: 'main')
  # git_pull
end

platform :ios do

  private_lane :staging_build do
      increment_build_number(xcodeproj: 'app_demo.xcodeproj')
      gym(scheme: 'app_demo-staging', workspace: 'app_demo.xcworkspace', clean: 'true')
  end


  lane :beta do
      staging_build
      # upload_to_testflight(username: 'youremail@gmail.com', app_identifier: 'ReactNativeFastlane')
      # commit_version_bump(message: 'bump build')
      # push_to_git_remote
  end

end