# Android Fastfile
default_platform(:android)
require_relative '../../fastlane_helper_methods/date_transformer'

# Ensures that fastfile only runs on main
before_all do
  ensure_git_branch(branch: 'main')
end

# Specifying that Android is the platform for where dependencies/settings apply
platform :android do
  
  # Lane used to run gradle tests
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  # Lane used to upload a new build to testflight
  desc "Submit a new Beta Build to internal testing"
  lane :beta do
    
    # Incrementing version code based on "%Y%m%d%H%M" - yyyymmddhhMM (where MM is minute and mm is month)
    increment_version_code("version_code": use_date_to_generate_number)
    
    # Create a release bundle
    gradle(
      task: 'bundle',
      build_type: 'Release'
    )
    
    # Upload release bundle to testflight
    upload_to_play_store(
      track: 'internal',
      skip_upload_apk: true,
      release_status: 'draft'
    )
  end
end
