# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  
  desc "Sets up project to be able to run necessary plugins"
  lane :setup do
    sh('echo | bundle exec fastlane add_plugin increment_version_code')
  end
  
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end
  
  desc "Upgrade Android Version"
  lane :upgrade_version do
    increment_version_code
  end

  desc "Submit a new Beta Build to internal testing"
  lane :beta do
    # NOTE: increment_version_code doesn't work yet
    gradle(
      task: 'bundle',
      build_type: 'Release'
    )
    upload_to_play_store(
      track: 'internal',
      skip_upload_apk: true,
      release_status: 'draft'
    )
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end
end
