name: Create build for Android and upload to playstore - new test
on:
  push:
    branches: ['main']
jobs:
  # ----------------------- ANDROID ----------------------------- TESTTTT
  # -------------------------------------------------------------
  build-prod-android:
    name: Build & ship android prod app
    runs-on: ${{ fromJSON('["ubuntu-latest", "self-hosted"]')[github.repository == 'github/docs-internal'] }}
    steps:
      # Step 1: Setup java and node
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 11
      - name: Set up NODE
        uses: actions/setup-node@v3
        with:
          node-version: 14 # using the .nvmrc file in future
      # Step 2: Configure gradel and gradle wrapper with cache
      - name: Cache Gradle Wrapper
        uses: actions/cache@v2
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
      - name: Cache Gradle Dependencies
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-caches-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-caches-
      # Step 3: Install node packages
      - name: Install node modules
        run: npm install
        env:
          CI: true
      # Step 4: Setup ruby
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7'
      # Step 5: Install bundler, and fastlane
      - name: Install Fastlane
        run: cd android && bundle install && cd ../
        env:
          CI: true
      # Step 6: Install reactnative community pacakge manually
      - name: Add @react-native-community manually
        run: npm add @react-native-community/cli-platform-android@7.0.1
        env:
          CI: true

      # Step 8: Fastlane build android
      - name: Build android App via fastlane
        run: cd android && fastlane beta
        env:
          CI: true
          CD: true
          ANDROID_KEYSTORE_FILE: ${{ secrets.ANDROID_KEYSTORE_FILE }}
          ANDROID_KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          ANDROID_KEYSTORE_ALIAS: ${{ secrets.ANDROID_KEYSTORE_ALIAS }}
